name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'
    - name: Install libssl1.1
      run: sudo apt-get update && sudo apt-get install -y libssl1.1
    - name: Restore dependencies
      run: dotnet restore WebBMI/WebBMI.sln
    - name: Build
      run: dotnet build WebBMI/WebBMI.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test WebBMI/WebBMI.sln --no-build --verbosity normal
